runtime: python312
entrypoint: gunicorn -b :$PORT county_secure_dashboard:server
instance_class: F2

env_variables:
  SNOWFLAKE_USER: 'mabel10'
  SNOWFLAKE_PASSWORD: 'Abvin!123456789'
  SNOWFLAKE_ACCOUNT: 'wthggzd-ah61676'
  SNOWFLAKE_WAREHOUSE: 'COMPUTE_WH'
  SNOWFLAKE_DATABASE: 'SUSTAINABILITY_DB'
  SNOWFLAKE_SCHEMA: 'PUBLIC'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10